name: test_dev_app_broseph
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  flutter_bloc: any
  dio: any
  url_launcher: any
  flutter_staggered_animations: any
  cached_network_image: any
  google_fonts: any
  card_loading: any
  delayed_display: any
  hive_flutter: any
  hive: any
  path_provider: any
  scroll_bottom_navigation_bar: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  cupertino_icons: any
  hive_generator: any
  build_runner: any


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

